### ISSUE TITLE
The latest update to chrome causes visual issues

### ISSUE THREAD

**Issue by skos-ninja** [eustasy/elementary-theme-for-google-chrome#2]
As shown below with the latest update to chrome they have now added the user to the right hand side of the chrome window which is not shown very well with it's border. [Screenshot](https://cloud.githubusercontent.com/assets/6642527/5770217/25b12c14-9d1f-11e4-80de-cbd336e0517e.png)

**Comment by lewisgoddard** [comment]
This doesn't happen if you use chrome borders instead of system borders. Unfortunately, we can't style the Gtk border around your window.
